name: ES-ui-upgrades
authors: Roger Tabris
homepage: https://github.com/lumbar527/es-ui-upgrades
license: GPL-3.0-or-later
version: 841bd780a8e8499670b83d120cdc7c70f174b214
shortDescription: A plugin that aims to transform the UI.
description: This plugin aims to be the first plugin to transform the UI. It tries
  to make it into a more digital interface, with floating transparent blue windows.
url: https://github.com/lumbar527/es-ui-upgrades/archive/841bd780a8e8499670b83d120cdc7c70f174b214.zip
iconUrl: https://github.com/lumbar527/es-ui-upgrades/raw/841bd780a8e8499670b83d120cdc7c70f174b214/icon.png
autoupdate:
  type: commit
  branch: main
  url: https://github.com/lumbar527/es-ui-upgrades/archive/$version.zip
  iconUrl: https://github.com/lumbar527/es-ui-upgrades/raw/$version/icon.png
